import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { cairo } from '@/app/[lang]/fonts';
import GlobalProvider from '@/providers';
import { dir } from 'i18next';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout(props) {
  const params = await props.params;

  const { lang } = params;
  console.log('dir(lang)...', dir(lang));
  const { children } = props;
  return (
    <html lang={lang} dir={dir(lang)}>
      <GlobalProvider lang={lang}>
        <body className={`${cairo.className}`}>{children}</body>
      </GlobalProvider>
    </html>
  );
}
