import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { cairo } from "@/app/[lang]/fonts";
import GlobalProvider from "@/providers";
import { i18nRouterConfig } from "@/localization/i18nRouterConfig";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout(props) {
  const params = await props.params;

  const { lang } = params;
  const direction = i18nRouterConfig.getDirection(lang);
  console.log("Language:", lang, "Direction:", direction);

  const { children } = props;
  return (
    <html lang={lang} dir={direction}>
      <GlobalProvider lang={lang}>
        <body className={`${cairo.className}`}>{children}</body>
      </GlobalProvider>
    </html>
  );
}
