import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { cairo } from "@/app/[lang]/fonts";
import GlobalProvider from "@/providers";
import { i18nRouterConfig } from "@/localization/i18nRouterConfig";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import "swiper/css";
import "swiper/css/free-mode";
import "swiper/css/navigation";
import "swiper/css/pagination";
import "swiper/css/scrollbar";
import "swiper/css/effect-fade";
import "swiper/css/effect-coverflow";
import "swiper/css/effect-flip";
import "swiper/css/effect-cube";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout(props) {
  const params = await props.params;

  const { lang } = params;
  const direction = i18nRouterConfig.getDirection(lang);
  console.log("Language:", lang, "Direction:", direction);

  const { children } = props;
  return (
    <html lang={lang} dir={direction}>
      <GlobalProvider lang={lang}>
        <body className={`${cairo.className}`}>
          <ToastContainer
            position="top-right"
            autoClose={5000}
            hideProgressBar={false}
            newestOnTop={false}
            closeOnClick
            rtl={direction === "rtl"}
            pauseOnFocusLoss
            draggable
            pauseOnHover
            theme="light"
          />
          {children}
        </body>
      </GlobalProvider>
    </html>
  );
}
